env: "local"
access_token_ttl: 1h
refresh_token_ttl: 48h
jwt_secret: example_secret
grpc:
  port: 44044
  timeout: 10h
postgres:
  host: "localhost"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbname: "chat_db"
  sslmode: "disable"
  max_conns: 10
  min_conns: 2
  connect_timeout: 5s